{"timestamp": "2017-11-27T10:59:27.066724Z", "level": "CRITICAL", "message": "Unhandled exception: %s", "system": "Darwin 17.2.0", "gh_handle": "pszandra8", "command": "/usr/local/bin/gf start https://github.com/greenfox-academy/teaching-materials/blob/master/workshop/expressions-and-control-flow/python.md", "feature": "START", "workshop_url": "https://github.com/greenfox-academy/teaching-materials/blob/master/workshop/expressions-and-control-flow/python.md", "language": null, "type": "<class 'FileNotFoundError'>", "value": "Exception: [Errno 2] No such file or directory: 'pip': 'pip'", "traceback": "File \"/usr/local/bin/gf\", line 11, in <module>\n    load_entry_point('workshop-toolchain==2.4.0', 'console_scripts', 'gf')()\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gf/app_starter.py\", line 15, in main\n    app_controller.run()\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gf/app_controller.py\", line 11, in run\n    task_check(get_command_argument())()\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gf/app_controller.py\", line 43, in start\n    start_service.main(get_filename())\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gf/start/start_service.py\", line 13, in main\n    prepare_to_start(url)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gf/start/start_service.py\", line 20, in prepare_to_start\n    check_app_version()\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gf/start/start_service.py\", line 33, in check_app_version\n    create_command_data_to_version_check())\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gf/verify/subprocess_adapter.py\", line 14, in run\n    input=input_string.encode())\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py\", line 403, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py\", line 709, in __init__\n    restore_signals, start_new_session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py\", line 1344, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)"}
